AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - lib/rubocop-readable_rails.rb
