# frozen_string_literal: true

require_relative "greppable_rails/dont_call_helper_in_controller"
require_relative "greppable_rails/dont_include_in_helper"
require_relative "greppable_rails/use_inline_access_modifier"
