# Common configuration.

inherit_mode:
  merge:
    - Exclude

GreppableRails/DontIncludeInHelper:
  Description: 'Prohibit include in Helper.'
  Enabled: true
  VersionAdded: '0.1.0'

GreppableRails/UseInlineAccessModifier:
  Description: 'Use inline style access modifier.'
  Enabled: true
  VersionAdded: '0.1.0'

