# Common configuration.

inherit_mode:
  merge:
    - Exclude

GreppableRails/DontIncludeInHelper:
  Description: 'Prohibit include in Helper.'
  Enabled: true
  VersionAdded: '0.1.0'
  Include:
    - app/helper/**/*.rb

GreppableRails/UseInlineAccessModifier:
  Description: 'Use inline style access modifier.'
  Enabled: true
  VersionAdded: '0.1.0'

GreppableRails/DontCallHelperInController:
  Description: 'Prohibit include helper via call helper in Controller.'
  Enabled: true
  VersionAdded: '0.1.0'
  Include:
    - app/controllers/**/*.rb
