name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2', '3.3', '3.4', '4.0', 'head' ]
    name: Test on Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1.307.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Execute rubocop
      run: bundle exec rake
    - name: Execute rspec
      run: bundle exec rspec
